name: nlp_hungover_pandas
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - pip:
    - bert_score==0.3.13
    - ipython==8.12.3
    - langchain_community==0.4.2
    - langchain_core==1.4.0
    - langchain_google_genai==4.2.3
    - langchain_huggingface==1.2.2
    - langchain_text_splitters==1.1.2
    - matplotlib==3.10.9
    - numpy==2.4.6
    - pandas==3.0.3
    - protobuf==7.35.0
    - python-dotenv==1.2.2
    - torch==2.12.0
    - transformers==5.9.0
    - sentence-transformers
    - faiss-cpu
    - faiss-gpu
    - jupyter
